### ISSUE TITLE
Case sensitive

### ISSUE THREAD

**Issue by tzagim** [Lash-L/RoborockCustomMap#4]
It seems that the platform should be defined with a capital R (Roborock NOT roborock), you and [lovelace-xiaomi-vacuum-map-card](https://github.com/PiotrMachowski/lovelace-xiaomi-vacuum-map-card) should fix the example.

```yaml
type: custom:xiaomi-vacuum-map-card
vacuum_platform: Roborock
entity: vacuum.s7
map_source:
  camera: image.s7_downstairs_full_custom
calibration_source:
  camera: true
```

Thank you for your wonderful work.
