### ISSUE TITLE
Invalid calibration when using a different floor image in Xiaomi Vacuum Map card

### ISSUE THREAD

**Issue by JohnyR** [Lash-L/RoborockCustomMap#6]
Hi,

When using any image other than my first floor's, the Xiaomi Vac card throws an "Invalid calibration" error.

I assume it's related to Calibration Points.

![Image](https://github.com/user-attachments/assets/6b9d7954-2631-47fe-9a3c-24a7b9f382d0)

**Comment by Lash-L** [comment]
You need to change which map is selected, and then the calibration points should exist. Give that a try and let me know how it goes

Potentially:

1. Use the select entity to select a new map - wait 30seconds)
2. try to review the image again
3. if that fails, reload the custom map integration (not Roborock)

once it gets the calibration points, it shouldn’t need to do it again until you restart

**Comment by JohnyR** [comment]
Hey @Lash-L, thanks for the quick reply.

I'm actually automatically changing the selected map when I load a new preset via:

```
activate_on_switch: true
activate:
  service: vacuum.send_command
  service_data:
    entity_id: vacuum.roborock_qrevo_pro
    command: load_multi_map
    params: 1
```

I can see that the selected floor is being changed on the Roborock integration, but the invalid calibration error persists even after the select entity updates and reloading the Custom Map integrations. Manually changing the select via the UI in the integration yields the same result.

**Comment by Lash-L** [comment]
If you reload the custom map integration do you still see the same effect?

**Comment by JohnyR** [comment]
Yup.

**Comment by Lash-L** [comment]
I've put some thought into the broken as I knew it was a problem going into it

Basically, map logic is relatively computationally expensive compared to everything else. So we do some caching. The actual image is cached to help keep compute time low when a user has multiple maps. 

What you can do is load the map, reload the Roborock integration, reload the custom map integration, and hit generate static config for the currently selected map. It will output your calibration points. This isn't ideal as if mapdata/ calibration significantly changes it will lead to problems but it would be a solution.

I'll keep this on my mind and see if I can come up with a solution I like

**Comment by Mikefila** [comment]
I am having problems with this too. The custom image entities loose their calibration points randomly. Reloading/restart/reinstall/install doesn't have any effect.

I was able to go into the history of the images and pull the calibration points. I then manually added them to the card. If your home is completely mapped and rooms defined, you shouldn't need to change it.

Where it says

```
calibration_source:
  camera: true
```

use the calibration and room points from the image attributes.

```
  calibration_source:
    calibration_points:
      - vacuum:
          x: 25500
          "y": 25500
        map:
          x: 1036
          "y": 516
      - vacuum:
          x: 35500
          "y": 25500
        map:
          x: 1836
          "y": 516
      - vacuum:
          x: 25500
          "y": 35500
        map:
          x: 1036
          "y": -284
  rooms:
    "16":
      x0: 18150
      y0: 19150
      x1: 22250
      y1: 22750
      number: 16
      name: Bedroom
      pos_x: null
      pos_y: null
      ...
```
