### ISSUE TITLE
Rotation and Background of the Image

### ISSUE THREAD

**Issue by Mar1usW3** [Lash-L/RoborockCustomMap#7]
Is there a way to rotate the picture and set the background as transparent?

**Comment by PiotrMachowski** [comment]
This integration doesn't process map data by itself - it uses map data that is already parsed by the built-in Roborock integration, so these functionalities would have to be added to the HA core instead.

**Comment by NewsGuyTor** [comment]
Yeah, this would be awesome, sorely missed ATM!

**Comment by Mar1usW3** [comment]
for my usecase i made it with card_mod+

```yaml
show_state: false
show_name: false
camera_view: auto
type: picture-entity
entity: image.robi_zu_hause_custom
aspect_ratio: "20:13"
card_mod:
  style: |
    ha-card {
      transform: rotate(180deg);
    }
```
